name: CmplxDsgn
favicon: null
layout_spectrum: 0.901944772573188
typography_spectrum: 0.8804276424925774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a5a5a'
    - '#fefefe'
    - '#8a8a8a'
    - '#dcdcdc'
    - '#c1c1c1'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
